// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuteq2B9aeV1uO8xHXdFPLRYxfLlyoBOU',
    appId: '1:233725212828:android:f320f8ab81f46b9a0d9559',
    messagingSenderId: '233725212828',
    projectId: 'budget-planning-639a2',
    databaseURL: 'https://budget-planning-639a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'budget-planning-639a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAinZMd_hu_6n7AowL1AN13YyLOIkxypk8',
    appId: '1:233725212828:ios:1e8fcb818d91c5c90d9559',
    messagingSenderId: '233725212828',
    projectId: 'budget-planning-639a2',
    databaseURL: 'https://budget-planning-639a2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'budget-planning-639a2.appspot.com',
    iosBundleId: 'budgetplanning.org.budgetPlanning',
  );
}
